#!/usr/bin/env python3
"""Embed Arpejo's real brand fonts into a .pptx generated by pptxgenjs (or
any tool), so the file renders correctly in PowerPoint/LibreOffice on a
machine that doesn't have the fonts installed — no "embed fonts in file"
step needed from Bianca.

This copies the *.fntdata parts straight out of assets/fonts/embed/ (lifted
byte-for-byte from Arpejo's own report .pptx, which already had these fonts
embedded by whatever tool built it — likely Canva) and wires them into the
target file's [Content_Types].xml, ppt/_rels/presentation.xml.rels, and
ppt/presentation.xml. It does not need to understand PowerPoint's font
obfuscation format — it only ever copies these opaque blobs, never edits
their bytes.

Usage:
  python embed_fonts.py deck.pptx
  python embed_fonts.py deck.pptx -o deck-with-fonts.pptx
"""
import argparse
import re
import shutil
import zipfile
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
FONT_DIR = SCRIPT_DIR.parent / "assets" / "fonts" / "embed"

# (typeface name PowerPoint expects, filename prefix in FONT_DIR)
FAMILIES = [
    ("JetBrains Mono Medium", "JetBrainsMonoMedium"),
    ("Urbanist", "Urbanist"),
    ("Libre Baskerville", "LibreBaskerville"),
    ("Ubuntu Mono", "UbuntuMono"),
]
STYLES = [("regular", "p:regular"), ("bold", "p:bold"), ("italic", "p:italic"), ("boldItalic", "p:boldItalic")]

FONT_REL_TYPE = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/font"


def next_rid(rels_xml):
    ids = [int(m) for m in re.findall(r'Id="rId(\d+)"', rels_xml)]
    return max(ids) + 1 if ids else 1


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("pptx")
    p.add_argument("-o", "--output")
    args = p.parse_args()

    src = Path(args.pptx)
    out = Path(args.output) if args.output else src

    missing = [f"{prefix}-{style}.fntdata" for _, prefix in FAMILIES for style, _ in STYLES
               if not (FONT_DIR / f"{prefix}-{style}.fntdata").exists()]
    if missing:
        raise SystemExit(f"missing font parts in {FONT_DIR}: {missing}")

    work = src.with_suffix(".embedfonts.tmp")
    if work.exists():
        shutil.rmtree(work)
    work.mkdir()

    with zipfile.ZipFile(src) as z:
        z.extractall(work)

    ct_path = work / "[Content_Types].xml"
    ct = ct_path.read_text(encoding="utf-8")
    if 'Extension="fntdata"' not in ct:
        ct = ct.replace("</Types>", '<Default ContentType="application/x-fontdata" Extension="fntdata"/></Types>')
        ct_path.write_text(ct, encoding="utf-8")

    rels_path = work / "ppt" / "_rels" / "presentation.xml.rels"
    rels = rels_path.read_text(encoding="utf-8")
    rid = next_rid(rels)

    fonts_dir = work / "ppt" / "fonts"
    fonts_dir.mkdir(exist_ok=True)

    embedded_font_lst = ["<p:embeddedFontLst>"]
    new_rels = []
    for typeface, prefix in FAMILIES:
        embedded_font_lst.append(f'<p:embeddedFont><p:font typeface="{typeface}"/>')
        for style, tag in STYLES:
            fname = f"{prefix}-{style}.fntdata"
            shutil.copy(FONT_DIR / fname, fonts_dir / fname)
            new_rels.append(
                f'<Relationship Id="rId{rid}" Type="{FONT_REL_TYPE}" Target="fonts/{fname}"/>'
            )
            embedded_font_lst.append(f'<{tag} r:id="rId{rid}"/>')
            rid += 1
        embedded_font_lst.append("</p:embeddedFont>")
    embedded_font_lst.append("</p:embeddedFontLst>")
    embedded_font_lst = "".join(embedded_font_lst)

    rels = rels.replace("</Relationships>", "".join(new_rels) + "</Relationships>")
    rels_path.write_text(rels, encoding="utf-8")

    pres_path = work / "ppt" / "presentation.xml"
    pres = pres_path.read_text(encoding="utf-8")
    if "embedTrueTypeFonts=" not in pres:
        pres = pres.replace("<p:presentation ", '<p:presentation embedTrueTypeFonts="1" ', 1)
    if "<p:embeddedFontLst>" not in pres:
        if "<p:defaultTextStyle" in pres:
            pres = pres.replace("<p:defaultTextStyle", embedded_font_lst + "<p:defaultTextStyle", 1)
        elif "<p:extLst" in pres:
            pres = pres.replace("<p:extLst", embedded_font_lst + "<p:extLst", 1)
        else:
            pres = pres.replace("</p:presentation>", embedded_font_lst + "</p:presentation>")
    pres_path.write_text(pres, encoding="utf-8")

    if out.exists():
        out.unlink()
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for f in sorted(work.rglob("*")):
            if f.is_file():
                z.write(f, f.relative_to(work))

    shutil.rmtree(work)
    print(f"embedded 4 font families (16 files) into {out}")


if __name__ == "__main__":
    main()
